/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package SlamBook;

import Util.Connect;
import java.awt.Image;
import java.awt.event.KeyEvent;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import java.io.File;
import java.io.FileInputStream;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.ImageIcon;
import java.io.ByteArrayOutputStream;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.Icon;
import javax.swing.table.DefaultTableModel;
import java.sql.*;
import java.util.Vector;
/**
 *
 * @author Kamaraj
 */
public class AddFriend extends javax.swing.JFrame {

    String filename = null;
byte[] Photo= null;
Connection sqlConn = null;
PreparedStatement pst = null;
ResultSet rs = null;
String PersonID,Name,FathersName,DOB,Gender,Age,Address,Happymoments,Phone ="";
int q,i ;
    /**
     * Creates new form AddFriend
     */
    public AddFriend() {
        initComponents();
        UpdateDB();
        showIdUser();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
       private void UpdateDB()
    {
        try
        {
           Class.forName("com.mysql.cj.jdbc.Driver");
            sqlConn = DriverManager.getConnection("jdbc:mysql://localhost:3306/myslam database","root","Subha");
             pst = sqlConn.prepareStatement("select * from personinfo");
             rs = pst.executeQuery();
             ResultSetMetaData stData = rs.getMetaData();
             q = stData.getColumnCount();
             DefaultTableModel RecordTable = (DefaultTableModel)CTable.getModel();
             RecordTable.setRowCount(0);
             
             while(rs.next()){
                 Vector columnData = new Vector();
                 
                 for (i =1;i<=q; i++)
                 {
                    columnData.add(rs.getInt("PersonID"));
                    columnData.add(rs.getString("Name"));
                    columnData.add(rs.getString("FathersName"));
                    columnData.add(rs.getString("DOB"));
                    columnData.add(rs.getString("Gender"));
                    columnData.add(rs.getString("Age"));
                    columnData.add(rs.getString("Address"));
                    columnData.add(rs.getString("Phone"));
                    columnData.add(rs.getString("Happymoments"));
                    columnData.add(rs.getBytes("Photo"));
                 }
                 RecordTable.addRow(columnData);
             }
             }catch(Exception ex){
            JOptionPane.showMessageDialog(null,ex);
        }
    }
       
       private void showIdUser() {
        Connect connecta = new Connect();
        connecta.connectexce();
       try{
           Class.forName("com.mysql.cj.jdbc.Driver");
            sqlConn = DriverManager.getConnection("jdbc:mysql://localhost:3306/myslam database","root","Subha");
           connecta.executeSQL("SELECT * FROM personinfo ORDER BY PersonID DESC LIMIT 1 ");
           connecta.rs.first();
           Cid.setText(String.valueOf(connecta.rs.getInt("PersonID")));
           int PersonID = Integer.parseInt(Cid.getText());
           PersonID++;
           Cid.setText(String.valueOf(PersonID));
       }catch(Exception e){
           
       }
    }
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel11 = new javax.swing.JLabel();
        Cid = new javax.swing.JTextField();
        LabPhoto = new javax.swing.JLabel();
        txt_path = new javax.swing.JTextField();
        Uploadbtn = new javax.swing.JButton();
        GoBack = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        CTable = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        Savebtn = new javax.swing.JButton();
        Deletebtn = new javax.swing.JButton();
        resetbtn = new javax.swing.JButton();
        CName = new javax.swing.JTextField();
        Cfather = new javax.swing.JTextField();
        Cdob = new javax.swing.JFormattedTextField();
        Cdob1 = new javax.swing.JFormattedTextField();
        Cmale = new javax.swing.JRadioButton();
        Cfemale = new javax.swing.JRadioButton();
        Cage = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        CAddress = new javax.swing.JTextArea();
        CPhn = new javax.swing.JTextField();
        Cmoments = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("ADD FRIEND");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel11.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel11.setText("Person ID");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 170, -1, -1));

        Cid.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        Cid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CidActionPerformed(evt);
            }
        });
        getContentPane().add(Cid, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 160, 100, 30));

        LabPhoto.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(LabPhoto, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 200, 330, 400));

        txt_path.setBackground(new java.awt.Color(0,0,0,1));
        txt_path.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txt_path.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_pathActionPerformed(evt);
            }
        });
        getContentPane().add(txt_path, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 600, 330, 30));

        Uploadbtn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Uploadbtn.setText("UploadPhoto");
        Uploadbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UploadbtnActionPerformed(evt);
            }
        });
        getContentPane().add(Uploadbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 640, -1, 30));

        GoBack.setBackground(new java.awt.Color(0,0,0,1)
        );
        GoBack.setForeground(new java.awt.Color(255, 255, 255));
        GoBack.setText("Go Back");
        GoBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GoBackActionPerformed(evt);
            }
        });
        getContentPane().add(GoBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        CTable.setBackground(new java.awt.Color(0,0,0,1));
        CTable.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        CTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "PersonID", "Name", "Father's Name", "DOB", "Gender", "Age", "Address", "Phone No.", "HappyMoments", "Photo"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.Byte.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        CTable.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        CTable.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        CTable.setDragEnabled(true);
        CTable.setSelectionBackground(new java.awt.Color(153, 153, 153));
        CTable.setSelectionForeground(new java.awt.Color(255, 255, 255));
        CTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CTableMouseClicked(evt);
            }
        });
        CTable.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                CTableKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                CTableKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(CTable);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 170, 510, 300));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel6.setText("Happy Moments");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 590, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel4.setText("Phone No.");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 530, 100, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Address");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 470, 130, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel8.setText("Age");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 400, -1, -1));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel10.setText("Gender");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 330, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel5.setText("DOB");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 280, -1, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel9.setText("Father's Name");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 230, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Name");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 180, 130, 30));

        Savebtn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Savebtn.setText("Save");
        Savebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SavebtnActionPerformed(evt);
            }
        });
        getContentPane().add(Savebtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 660, -1, -1));

        Deletebtn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Deletebtn.setText("Delete");
        Deletebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeletebtnActionPerformed(evt);
            }
        });
        getContentPane().add(Deletebtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 660, -1, -1));

        resetbtn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        resetbtn.setText("Reset");
        resetbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetbtnActionPerformed(evt);
            }
        });
        getContentPane().add(resetbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 660, -1, -1));

        CName.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        CName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CNameActionPerformed(evt);
            }
        });
        CName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                CNameKeyPressed(evt);
            }
        });
        getContentPane().add(CName, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 180, 170, 30));

        Cfather.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        Cfather.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CfatherActionPerformed(evt);
            }
        });
        Cfather.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                CfatherKeyPressed(evt);
            }
        });
        getContentPane().add(Cfather, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 230, 170, 30));

        try {
            Cdob.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("####-##-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        Cdob.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        Cdob.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CdobActionPerformed(evt);
            }
        });
        getContentPane().add(Cdob, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 282, 170, 30));

        try {
            Cdob1.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("####-##-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        Cdob1.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        Cdob1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Cdob1ActionPerformed(evt);
            }
        });
        getContentPane().add(Cdob1, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 282, 170, 30));

        Cmale.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        Cmale.setForeground(new java.awt.Color(0, 204, 255));
        Cmale.setText("Male");
        Cmale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CmaleActionPerformed(evt);
            }
        });
        getContentPane().add(Cmale, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 330, 80, -1));

        Cfemale.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        Cfemale.setForeground(new java.awt.Color(255, 0, 255));
        Cfemale.setText("Female");
        Cfemale.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                CfemaleKeyPressed(evt);
            }
        });
        getContentPane().add(Cfemale, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 330, -1, -1));

        Cage.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        Cage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CageActionPerformed(evt);
            }
        });
        Cage.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                CageKeyPressed(evt);
            }
        });
        getContentPane().add(Cage, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 390, 170, -1));

        CAddress.setColumns(20);
        CAddress.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        CAddress.setRows(5);
        jScrollPane2.setViewportView(CAddress);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 460, 170, 60));

        CPhn.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        CPhn.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                CPhnKeyPressed(evt);
            }
        });
        getContentPane().add(CPhn, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 530, 170, -1));

        Cmoments.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        Cmoments.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                CmomentsKeyPressed(evt);
            }
        });
        getContentPane().add(Cmoments, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 590, 170, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Backgrounds/Addslambg (1).jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 1600, 970));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CidActionPerformed

    private void txt_pathActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_pathActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_pathActionPerformed

    private void UploadbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UploadbtnActionPerformed
        JFileChooser chooser = new JFileChooser();
        chooser.showOpenDialog(null);
        File f=chooser.getSelectedFile();
        filename = f.getAbsolutePath();
        txt_path.setText(filename);
        ImageIcon imageIcon = new ImageIcon(new ImageIcon(filename).getImage().getScaledInstance(LabPhoto.getWidth(),LabPhoto.getHeight(),Image.SCALE_SMOOTH));
        LabPhoto.setIcon(imageIcon);
        try{
            File image = new File(filename);
            FileInputStream fis = new FileInputStream(image);
            ByteArrayOutputStream bos = new ByteArrayOutputStream();
            byte[] buf = new byte[1024];
            for(int readNum;(readNum=fis.read(buf))!=-1;){
                bos.write(buf,0,readNum);
            }
            Photo=bos.toByteArray();
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null,e);
        }
    }//GEN-LAST:event_UploadbtnActionPerformed

    private void GoBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GoBackActionPerformed
        Home H = new Home();
        H.show();
        dispose();
    }//GEN-LAST:event_GoBackActionPerformed

    private void SavebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SavebtnActionPerformed
        
        try{
            Class.forName("com.mysql.cj.jdbc.Driver");
            sqlConn = DriverManager.getConnection("jdbc:mysql://localhost:3306/myslam database","root","Subha");
            String query = "Insert into personinfo(PersonID, Name , FathersName,DOB,Gender,Age,Address,Phone,Happymoments,Photo)values(?,?,?,?,?,?,?,?,?,?)";
            pst = sqlConn.prepareStatement(query);
            pst.setInt(1,Integer.parseInt(Cid.getText()));
            pst.setString(2,CName.getText());
            pst.setString(3,Cfather.getText());
            pst.setString(4,Cdob.getText());
            if(Cmale.isSelected()){
                Gender="Male";
            }
            if(Cfemale.isSelected()){
                Gender="Female";
            }
            pst.setString(5, Gender);
            pst.setString(6,Cage.getText());
            pst.setString(7,CAddress.getText());
            pst.setString(8,CPhn.getText());
            pst.setString(9,Cmoments.getText());
            pst.setBytes(10,Photo);
            pst.executeUpdate();
            JOptionPane.showMessageDialog(null,"Info Saved Successfully");
            UpdateDB();
            showIdUser();
            
        }
        catch (Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_SavebtnActionPerformed

    private void DeletebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeletebtnActionPerformed
        DefaultTableModel RecordTable = (DefaultTableModel)CTable.getModel();
        int SelectedRows = CTable.getSelectedRow();
        try{
            int response = JOptionPane.showConfirmDialog(null,"Confirm if you want to Delete Info","Warning",JOptionPane.YES_NO_OPTION);
            if(response == JOptionPane.YES_OPTION)
            {
                Class.forName("com.mysql.cj.jdbc.Driver");
                sqlConn = DriverManager.getConnection("jdbc:mysql://localhost:3306/myslam database","root","Subha");
                String query = "delete from personinfo where PersonID=?";
                pst = sqlConn.prepareStatement(query);
                pst.setInt(1,Integer.parseInt(Cid.getText()));
                pst.executeUpdate();
                JOptionPane.showMessageDialog(null,"Info deleted Sucessfully");
                CName.setText("");
                Cfather.setText("");
                Cdob.setText("");
                Cmale.setSelected(false);
                Cfemale.setSelected(false);
                CAddress.setText("");
                Cage.setText("");
                Cmoments.setText("");
                Cid.setText("");
                CPhn.setText("");
                LabPhoto.setIcon(null);
                txt_path.setText("");
                showIdUser();
                UpdateDB();
            }
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(AddFriend.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(AddFriend.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_DeletebtnActionPerformed

    private void resetbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetbtnActionPerformed
        CName.setText("");
        Cfather.setText("");
        Cdob.setText("");
        Cmale.setSelected(false);
        Cfemale.setSelected(false);
        CAddress.setText("");
        Cage.setText("");
        Cmoments.setText("");
        Cid.setText("");
        CPhn.setText("");
        LabPhoto.setIcon(null);
        txt_path.setText("");
        showIdUser();
    }//GEN-LAST:event_resetbtnActionPerformed

    private void CNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CNameActionPerformed

    private void CNameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_CNameKeyPressed
        int key=evt.getKeyCode();
        if(key==10){
            Cfather.requestFocus();
        }
    }//GEN-LAST:event_CNameKeyPressed

    private void CfatherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CfatherActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CfatherActionPerformed

    private void CfatherKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_CfatherKeyPressed
        int key=evt.getKeyCode();
        if(key==10){
            Cdob.requestFocus();
        }
    }//GEN-LAST:event_CfatherKeyPressed

    private void CdobActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CdobActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CdobActionPerformed

    private void Cdob1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Cdob1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Cdob1ActionPerformed

    private void CmaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CmaleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CmaleActionPerformed

    private void CfemaleKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_CfemaleKeyPressed
        int key=evt.getKeyCode();
        if(key==10){
            Cage.requestFocus();
        }
    }//GEN-LAST:event_CfemaleKeyPressed

    private void CageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CageActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CageActionPerformed

    private void CageKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_CageKeyPressed
        int key=evt.getKeyCode();
        if(key==10){
            CAddress.requestFocus();
        }
    }//GEN-LAST:event_CageKeyPressed

    private void CPhnKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_CPhnKeyPressed
        int key=evt.getKeyCode();
        if(key==10){
            Cmoments.requestFocus();
        }
    }//GEN-LAST:event_CPhnKeyPressed

    private void CmomentsKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_CmomentsKeyPressed
        int key=evt.getKeyCode();
        if(key==10){
            Savebtn.requestFocus();
        }
    }//GEN-LAST:event_CmomentsKeyPressed

    private void CTableKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_CTableKeyReleased
        if((evt.getKeyCode()==KeyEvent.VK_UP) || (evt.getKeyCode() == KeyEvent.VK_DOWN)){
            DefaultTableModel RecordTable = (DefaultTableModel)CTable.getModel();
            int SelectedRows = CTable.getSelectedRow();
            String Table_click =(CTable.getModel().getValueAt(SelectedRows,0).toString());
            try{
                Class.forName("com.mysql.cj.jdbc.Driver");
            sqlConn = DriverManager.getConnection("jdbc:mysql://localhost:3306/myslam database","root","Subha");
                String query ="select Photo from personinfo where PersonID = '"+Table_click+"'";
                pst = sqlConn.prepareStatement(query);
                rs = pst.executeQuery();
                if(rs.next()){
                    LabPhoto.setIcon((Icon) RecordTable.getValueAt(SelectedRows, 9));
                    byte[] Photo = rs.getBytes("Photo");
                    ImageIcon imageIcon = new ImageIcon(new ImageIcon(filename).getImage().getScaledInstance(LabPhoto.getWidth(),LabPhoto.getHeight(),Image.SCALE_SMOOTH));
                    LabPhoto.setIcon(imageIcon);
                    txt_path.setText(filename);
                }
            }catch(Exception e)
            {
                e.printStackTrace();
            }
            try{
                Class.forName("com.mysql.cj.jdbc.Driver");
            sqlConn = DriverManager.getConnection("jdbc:mysql://localhost:3306/myslam database","root","Subha");
                String query ="select * from personinfo where PersonID = '"+Table_click+"'";
                pst = sqlConn.prepareStatement(query);
                rs = pst.executeQuery();
                if(rs.next()){
                    Cid.setText(RecordTable.getValueAt(SelectedRows, 0).toString());
                    CName.setText(RecordTable.getValueAt(SelectedRows, 1).toString());
                    Cfather.setText(RecordTable.getValueAt(SelectedRows, 2).toString());
                    Cdob.setText(RecordTable.getValueAt(SelectedRows, 3).toString());
                    String Gender =(RecordTable.getValueAt(SelectedRows, 4).toString());
                    if(Gender.equals("Male")){
                        Cmale.setSelected(true);
                        Cfemale.setSelected(false);
                    }
                    else{
                        Cmale.setSelected(false);
                        Cfemale.setSelected(true);
                    }
                    Cage.setText(RecordTable.getValueAt(SelectedRows, 5).toString());
                    CAddress.setText(RecordTable.getValueAt(SelectedRows, 6).toString());
                    Cmoments.setText(RecordTable.getValueAt(SelectedRows, 8).toString());
                    CPhn.setText(RecordTable.getValueAt(SelectedRows, 7).toString());
                }
            }
            catch(Exception e){
            }
        }
    }//GEN-LAST:event_CTableKeyReleased

    private void CTableKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_CTableKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_CTableKeyPressed

    private void CTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CTableMouseClicked

        DefaultTableModel RecordTable = (DefaultTableModel)CTable.getModel();
        int SelectedRows = CTable.getSelectedRow();
        String Table_click =(CTable.getModel().getValueAt(SelectedRows,0).toString());

        try{
            Class.forName("com.mysql.cj.jdbc.Driver");
            sqlConn = DriverManager.getConnection("jdbc:mysql://localhost:3306/myslam database","root","Subha");
            String query ="select * from personinfo where PersonID = '"+Table_click+"'";
            pst = sqlConn.prepareStatement(query);
            rs = pst.executeQuery();
            if(rs.next()){
                Cid.setText(RecordTable.getValueAt(SelectedRows, 0).toString());
                CName.setText(RecordTable.getValueAt(SelectedRows, 1).toString());
                Cfather.setText(RecordTable.getValueAt(SelectedRows, 2).toString());
                Cdob.setText(RecordTable.getValueAt(SelectedRows, 3).toString());
                String Gender =(RecordTable.getValueAt(SelectedRows, 4).toString());
                if(Gender.equals("Male")){
                    Cmale.setSelected(true);
                    Cfemale.setSelected(false);
                }
                else{
                    Cmale.setSelected(false);
                    Cfemale.setSelected(true);
                }
                Cage.setText(RecordTable.getValueAt(SelectedRows, 5).toString());
                CAddress.setText(RecordTable.getValueAt(SelectedRows, 6).toString());
                Cmoments.setText(RecordTable.getValueAt(SelectedRows, 8).toString());
                CPhn.setText(RecordTable.getValueAt(SelectedRows, 7).toString());
            }
        }
        catch(Exception e){
        }
    }//GEN-LAST:event_CTableMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddFriend.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddFriend.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddFriend.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddFriend.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddFriend().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea CAddress;
    private javax.swing.JTextField CName;
    private javax.swing.JTextField CPhn;
    private javax.swing.JTable CTable;
    private javax.swing.JTextField Cage;
    private javax.swing.JFormattedTextField Cdob;
    private javax.swing.JFormattedTextField Cdob1;
    private javax.swing.JTextField Cfather;
    private javax.swing.JRadioButton Cfemale;
    private javax.swing.JTextField Cid;
    private javax.swing.JRadioButton Cmale;
    private javax.swing.JTextField Cmoments;
    private javax.swing.JButton Deletebtn;
    private javax.swing.JButton GoBack;
    private javax.swing.JLabel LabPhoto;
    private javax.swing.JButton Savebtn;
    private javax.swing.JButton Uploadbtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton resetbtn;
    private javax.swing.JTextField txt_path;
    // End of variables declaration//GEN-END:variables
}
