
package SlamBook;

import java.awt.Image;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


public class Frienddetails extends javax.swing.JFrame {
String filename = null;
Connection sqlConn = null;
PreparedStatement pst = null;
ResultSet rs = null;
byte[] person_image = null;
int q,i ;
    /**
     * Creates new form DetectionPage
     */

    public Frienddetails() {
        initComponents();
         UpdateDB();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
      private void UpdateDB()
    {
        try
        {
           Class.forName("com.mysql.cj.jdbc.Driver");
            sqlConn = DriverManager.getConnection("jdbc:mysql://localhost:3306/myslam database","root","Subha");
             pst = sqlConn.prepareStatement("select * from personinfo");
             rs = pst.executeQuery();
             ResultSetMetaData stData = rs.getMetaData();
             q = stData.getColumnCount();
             DefaultTableModel RecordTable = (DefaultTableModel)DTable.getModel();
             RecordTable.setRowCount(0);
             
             while(rs.next()){
                 Vector columnData = new Vector();
                 
                 for (i =1;i<=q; i++)
                 {
                    columnData.add(rs.getInt("PersonID"));
                    columnData.add(rs.getString("Name"));
                    columnData.add(rs.getString("FathersName"));
                    columnData.add(rs.getString("DOB"));
                    columnData.add(rs.getString("Gender"));
                    columnData.add(rs.getString("Age"));
                    columnData.add(rs.getString("Address"));
                    columnData.add(rs.getString("Phone"));
                    columnData.add(rs.getString("Happymoments"));
                    columnData.add(rs.getBytes("Photo"));
                 }
                 RecordTable.addRow(columnData);
             }
             }catch(Exception ex){
            JOptionPane.showMessageDialog(null,ex);
        }
    }
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        GoBackButtn = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        DName = new javax.swing.JTextField();
        DId = new javax.swing.JTextField();
        DFather = new javax.swing.JTextField();
        DAge = new javax.swing.JTextField();
        DAddress = new java.awt.TextArea();
        jLabel9 = new javax.swing.JLabel();
        DPhn = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        Dmoments = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        DGender = new javax.swing.JTextField();
        Ddob = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        DTable = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("FRIENDS DETAILS");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        GoBackButtn.setForeground(new java.awt.Color(255, 255, 255));
        GoBackButtn.setText("Go Back");
        GoBackButtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GoBackButtnActionPerformed(evt);
            }
        });
        getContentPane().add(GoBackButtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
        GoBackButtn.setBackground(new java.awt.Color(0,0,0,1));

        jPanel1.setBackground(new java.awt.Color(0,0,0,1));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Person Details", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 3, 18), new java.awt.Color(255, 153, 153))); // NOI18N
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setText("Name");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 50, 80, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setText("ID");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 100, 50, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setText("Father's Name");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 150, -1, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel6.setText("DOB");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 200, 50, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel7.setText("Age");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 350, 60, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel8.setText("Address");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 420, -1, -1));

        DName.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        DName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DNameActionPerformed(evt);
            }
        });
        jPanel1.add(DName, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 50, 170, -1));

        DId.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jPanel1.add(DId, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 100, 170, -1));

        DFather.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jPanel1.add(DFather, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 150, 170, -1));

        DAge.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jPanel1.add(DAge, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 360, 170, -1));

        DAddress.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jPanel1.add(DAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 410, 170, 50));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel9.setText("Phone No.");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 300, -1, -1));

        DPhn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jPanel1.add(DPhn, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 300, 170, -1));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Happy Moments");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 510, 150, 40));

        Dmoments.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Dmoments.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DmomentsActionPerformed(evt);
            }
        });
        jPanel1.add(Dmoments, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 520, 170, 70));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setText("Gender");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 250, -1, -1));

        DGender.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        DGender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DGenderActionPerformed(evt);
            }
        });
        jPanel1.add(DGender, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 250, 170, -1));

        Ddob.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Ddob.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DdobActionPerformed(evt);
            }
        });
        jPanel1.add(Ddob, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 200, 170, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 120, 690, 650));

        DTable.setBackground(new java.awt.Color(0,0,0,1));
        DTable.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        DTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "PersonID", "Name", "Father's Name", "DOB", "Gender", "Age", "Address", "Phone No.", "HappyMoments", "Photo"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.Byte.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        DTable.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        DTable.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        DTable.setDragEnabled(true);
        DTable.setSelectionBackground(new java.awt.Color(153, 153, 153));
        DTable.setSelectionForeground(new java.awt.Color(255, 255, 255));
        DTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DTableMouseClicked(evt);
            }
        });
        DTable.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                DTableKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                DTableKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(DTable);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 170, 510, 300));

        jLabel1.setBackground(new java.awt.Color(0,0,0,1));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Backgrounds/Frienddetailsbg (1).jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -30, 1590, 990));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void GoBackButtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GoBackButtnActionPerformed
        // TODO add your handling code here:
         Home second = new Home();
        second.show();
        dispose();
         
    }//GEN-LAST:event_GoBackButtnActionPerformed

    private void DNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DNameActionPerformed

    private void DmomentsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DmomentsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DmomentsActionPerformed

    private void DTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DTableMouseClicked

        DefaultTableModel RecordTable = (DefaultTableModel)DTable.getModel();
        int SelectedRows = DTable.getSelectedRow();
        String Table_click =(DTable.getModel().getValueAt(SelectedRows,0).toString());

        try{
             Class.forName("com.mysql.cj.jdbc.Driver");
            sqlConn = DriverManager.getConnection("jdbc:mysql://localhost:3306/myslam database","root","Subha");
            String query ="select * from personinfo where PersonID = '"+Table_click+"'";
            pst = sqlConn.prepareStatement(query);
            rs = pst.executeQuery();
            if(rs.next()){
                DId.setText(RecordTable.getValueAt(SelectedRows, 0).toString());
                DName.setText(RecordTable.getValueAt(SelectedRows, 1).toString());
                DFather.setText(RecordTable.getValueAt(SelectedRows, 2).toString());
                Ddob.setText(RecordTable.getValueAt(SelectedRows, 3).toString());
                DGender.setText(RecordTable.getValueAt(SelectedRows, 4).toString());
                DAge.setText(RecordTable.getValueAt(SelectedRows, 5).toString());
                DAddress.setText(RecordTable.getValueAt(SelectedRows, 6).toString());
                Dmoments.setText(RecordTable.getValueAt(SelectedRows, 8).toString());
                DPhn.setText(RecordTable.getValueAt(SelectedRows, 7).toString());
     
            }
        }
        catch(Exception e){
        }
    }//GEN-LAST:event_DTableMouseClicked

    private void DTableKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_DTableKeyPressed
        // TODO add your handling code here:

    }//GEN-LAST:event_DTableKeyPressed

    private void DTableKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_DTableKeyReleased
        if((evt.getKeyCode()==KeyEvent.VK_UP) || (evt.getKeyCode() == KeyEvent.VK_DOWN)){
            DefaultTableModel RecordTable = (DefaultTableModel)DTable.getModel();
            int SelectedRows = DTable.getSelectedRow();
            String Table_click =(DTable.getModel().getValueAt(SelectedRows,0).toString());
          
            try{
                Class.forName("com.mysql.cj.jdbc.Driver");
            sqlConn = DriverManager.getConnection("jdbc:mysql://localhost:3306/myslam database","root","Subha");
                String query ="select * from personinfo where PersonID = '"+Table_click+"'";
                pst = sqlConn.prepareStatement(query);
                rs = pst.executeQuery();
                if(rs.next()){
                    DId.setText(RecordTable.getValueAt(SelectedRows, 0).toString());
                    DName.setText(RecordTable.getValueAt(SelectedRows, 1).toString());
                    DFather.setText(RecordTable.getValueAt(SelectedRows, 2).toString());
                    Ddob.setText(RecordTable.getValueAt(SelectedRows, 3).toString());
                    DGender.setText(RecordTable.getValueAt(SelectedRows, 4).toString());
                    DAge.setText(RecordTable.getValueAt(SelectedRows, 5).toString());
                    DAddress.setText(RecordTable.getValueAt(SelectedRows, 6).toString());
                    Dmoments.setText(RecordTable.getValueAt(SelectedRows, 8).toString());
                    DPhn.setText(RecordTable.getValueAt(SelectedRows, 7).toString());
                    
                }
            }
            catch(Exception e){
            }
        }
    }//GEN-LAST:event_DTableKeyReleased

    private void DGenderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DGenderActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DGenderActionPerformed

    private void DdobActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DdobActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DdobActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frienddetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frienddetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frienddetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frienddetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        
        
    //</editor-fold
   
    /* Create and display the form */
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Frienddetails().setVisible(true);
            }
        });
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.TextArea DAddress;
    private javax.swing.JTextField DAge;
    private javax.swing.JTextField DFather;
    private javax.swing.JTextField DGender;
    private javax.swing.JTextField DId;
    private javax.swing.JTextField DName;
    private javax.swing.JTextField DPhn;
    private javax.swing.JTable DTable;
    private javax.swing.JTextField Ddob;
    private javax.swing.JTextField Dmoments;
    private javax.swing.JButton GoBackButtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
